/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreElProyectoRouteImport } from './routes/sobre-el-proyecto'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrincipiosSlugRouteImport } from './routes/principios.$slug'

const SobreElProyectoRoute = SobreElProyectoRouteImport.update({
  id: '/sobre-el-proyecto',
  path: '/sobre-el-proyecto',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipiosSlugRoute = PrincipiosSlugRouteImport.update({
  id: '/principios/$slug',
  path: '/principios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-el-proyecto': typeof SobreElProyectoRoute
  '/principios/$slug': typeof PrincipiosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-el-proyecto': typeof SobreElProyectoRoute
  '/principios/$slug': typeof PrincipiosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-el-proyecto': typeof SobreElProyectoRoute
  '/principios/$slug': typeof PrincipiosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/sobre-el-proyecto' | '/principios/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/sobre-el-proyecto' | '/principios/$slug'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/sobre-el-proyecto'
    | '/principios/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreElProyectoRoute: typeof SobreElProyectoRoute
  PrincipiosSlugRoute: typeof PrincipiosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-el-proyecto': {
      id: '/sobre-el-proyecto'
      path: '/sobre-el-proyecto'
      fullPath: '/sobre-el-proyecto'
      preLoaderRoute: typeof SobreElProyectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principios/$slug': {
      id: '/principios/$slug'
      path: '/principios/$slug'
      fullPath: '/principios/$slug'
      preLoaderRoute: typeof PrincipiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreElProyectoRoute: SobreElProyectoRoute,
  PrincipiosSlugRoute: PrincipiosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
